# Generated by Django 5.0.7 on 2024-07-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('description', models.TextField()),
                ('total_likes', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('totalComments', models.PositiveBigIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('totalReplies', models.PositiveBigIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_api.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('reply', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_api.comment')),
            ],
        ),
    ]
